version: '3.9'
services:
  homeassistant:
    image: homeassistant/home-assistant
    container_name: home-assistant
    volumes:
      - ./config/home-assistant:/config
    environment:
      - TZ=America/Los_Angeles
    ports:
      - "8123:8123"
    networks:
      - local_network

  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    restart: unless-stopped
    tmpfs:
      - /tmp/cache
    shm_size: 64m
    volumes:
      - ./storage/frigate:/media/frigate
      - ./config/frigate:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - FRIGATE_RTSP_USERNAME=borrego # Aun no se configura
      - FRIGATE_RTSP_PASSWORD=123456 # Aun no se configura
    ports:
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    networks:
      - local_network

  rtsp_server:
    image: bluenviron/mediamtx
    container_name: rtsp_server
    networks:
      - local_network

  fake_camera:
    image: alpine:latest
    container_name: fake_camera
    volumes:
      - ./storage/streams:/storage
    command: >
      /bin/sh -c "apk add --no-cache ffmpeg && sleep 10 && ffmpeg -stream_loop -1 -re -i /storage/stream.mp4 -c copy -f rtsp -loglevel debug rtsp://rtsp_server:8554/live/stream"
    networks:
      - local_network

networks:
  local_network:
    name: local_network
    driver: bridge