# yaml-language-server: $schema=http://frigate_host:5000/api/config/schema.json
mqtt:
  enabled: True

cameras:
  my_virtual_camera:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://rtsp_server:8554/live/stream
          roles:
            - detect
            - clip
            - record