
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# TODO: Investigar como integrar frigate a home assistant.
camera:
  - platform: ffmpeg
    name: Fake Camera
    input: rtsp://rtsp_server:8554/live/stream

# May not be needed
# http:
#   server_port: 8123
