
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# TODO: Investigar como integrar frigate a home assistant.
camera:
  - platform: ffmpeg
    name: Frigate Camera
    input: http://frigate:5000/live/my_virtual_camera/index.m3u8

# May not be needed
# http:
#   server_port: 8123
